### ISSUE TITLE
can not find openssl.hmac

### ISSUE THREAD

**Issue by xiaodong1978** [brightwang/kong-upstream-hmac#1]
CentOS 7.5  and kong 2.1.0

luarocks install kong-upstream-hmac 
kong start

Error: /usr/local/share/lua/5.1/kong/cmd/start.lua:64: nginx: [warn] load balancing method redefined in /usr/local/kong/nginx-kong.conf:56
nginx: [error] init_by_lua error: /usr/local/share/lua/5.1/kong/tools/utils.lua:625: error loading module 'kong.plugins.kong-upstream-hmac.handler':
...share/lua/5.1/kong/plugins/kong-upstream-hmac/access.lua:4: module 'openssl.hmac' not found:No LuaRocks module found for openssl.hmac

---------------------------------------------------

I have resolved this error by:
change access.lua line 4： local openssl_hmac = require "openssl.hmac" to local openssl_hmac = require "resty.openssl.hmac"

**Comment by xiaodong1978** [comment]
resolved

**Comment by brightwang** [comment]
> resolved

ok,i had never test it in 2.x
